language: java
jdk:
- openjdk11
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_7ea01d072007_key -iv $encrypted_7ea01d072007_iv
  -in application-database.properties.enc -out src/main/resources/application-database.properties
  -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dahyun_ee@naver.com
