INSERT INTO USERS(USER_ID, USER_EMAIL, PASSWORD, USER_ROLE)
VALUES(1, 'admin@example.com', '1234', 'ROLE_USER');

INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITIES(AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');
