--INSERT INTO users(USER_ID, USER_EMAIL, PASSWORD, USER_ROLE)
--VALUES(1, 'admin@example.com', '1234', 'ROLE_USER');

--INSERT INTO pets(PET_ID, USER_ID, PET_NAME, PET_GENDER, PET_WEIGHT, PET_BIRTHDATE)
--VALUES(1,1,'JJIGAE', 'FEMALE', 11.2, '2019-07-10')

SELECT * FROM users;